column_width = 80      # Maximum line width
line_endings = "Unix"  # Use Unix line endings (\n)
indent_type = "Spaces" # Use spaces for indentation
indent_width = 2       # 2 spaces per indent level

quote_style = "AutoPreferSingle"
# Function call formatting
call_parentheses = "Always" # Always include parentheses in function calls

# Table formatting
collapse_simple_statement = "Never" # Don't collapse simple statements
